### ISSUE TITLE
`Surface::lock_front_buffer` fails when `ffi::gbm_surface_lock_front_buffer` succeeds

### ISSUE THREAD

**Issue by tronical** [Smithay/gbm.rs#36]
I'm trying to use gbm.rs on an i.mx 8 series device with a Vivante GPU and corresponding drivers (6.4.3.p4.4). These come now with DRM support and a GBM backend (libgbm_viv.so).

C/C++ based programs like Weston, kmscube, mutter, or Qt's eglfs renderer work perfectly well on the device, but I noticed that using gbm.rs always fails in one spot:

`Surface::lock_front_buffer()` works the first time it is called, but the second time it is called it _always_ fails. I tracked it down to the call to `gbm_surface_has_free_buffers` failing.

I noticed that the above mentioned never call `gbm_surface_has_free_buffers` before calling `gbm_surface_lock_front_buffer` but go straight to `gbm_surface_lock_front_buffer` and check the return value.

If I change gbm.rs to do the same, i.e. omit the explicit call to `gbm_surface_has_free_buffers`, everything works expected (acquisition of buffers from the surface, rendering into it, posting, waiting for page flip event, etc.).

My feeling is that that `has_free_buffers` should return true (so this might be a driver bug), but it's hard to find exact document semantics, and it's strange that nobody else is calling it.

I'd be happy to make a PR to remove the call (and enum variant), but I wanted to check with you first.

**Comment by Drakulix** [comment]
Sorry for not answering earlier. I think this is an acceptable work-around for something I would also consider a driver bug. Feel free to submit a PR for that.

**Comment by tronical** [comment]
No worries, and thanks for confirming - much appreciated. I'll prepare that :)
